{
 "title": "PSY Traveler Events Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "airport", "label": "airport", "query": "ORD" }
  ]
 },
 "panels": [
  {
   "title": "Airport Events",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(\"TS\"/120)*120 AS \"time\",\ncount(\"AIRPORT\") as counter,\n\"AIRPORT\" as airport\nFROM \"USER_EVENTS_AVRO\"\nGROUP BY   time, airport\nORDER BY time asc\nLIMIT 2000"
    }
   ]
  },
  {
   "title": "Traveler Statuses for $airport",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"STATUS\" as \"Traveler Status\", COUNT(\"STATUS\") as \"Total\" FROM \"USER_EVENTS_AVRO\" where \"AIRPORT\" = '$airport' GROUP BY \"STATUS\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "$airport EVENTS",
   "type": "table",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select \n\"ROWTIME_FORMATTED\" as \"EVENT TIME\", \"STATUS\",\"FIRST_NAME\", \"LAST_NAME\", \"GENDER\", \"AGE\", \"EYECOLOR\", \"EMAIL\", \"PHONE_NUMBER\", \"STREET_ADDRESS\", \"STATE\", \"ZIP_CODE\", \"COUNTRY\"\n\n\nfrom \"USER_EVENTS_AVRO\" WHERE \"AIRPORT\" = '$airport' ORDER BY \"TS\" DESC"
    }
   ]
  }
 ]
}